### ISSUE TITLE
block parse failure for mainnet block 12c1f09d72c232659022fc67ab2bbe1a6db498817d0dd1d751dd6acf5ae1aa38

### ISSUE THREAD

**Issue by agaffney** [blinklabs-io/gouroboros#232]
We get a panic from deep-ish in the CBOR library.

```
panic: runtime error: hash of unhashable type []interface {}
```

https://cexplorer.io/block/12c1f09d72c232659022fc67ab2bbe1a6db498817d0dd1d751dd6acf5ae1aa38

**Comment by agaffney** [comment]
```
$ ./block-fetch -address relays-new.cardano-mainnet.iohk.io:3001 -network mainnet -ntn -slot 4563840 -hash 12c1f09d72c232659022fc67ab2bbe1a6db498817d0dd1d751dd6acf5ae1aa38
panic: runtime error: hash of unhashable type []interface {}

goroutine 28 [running]:
reflect.mapassign(0x670120, 0xc000198c50?, 0x0?, 0x6b9312?)
        /usr/local/go/src/runtime/map.go:1351 +0x25
reflect.Value.SetMapIndex({0x670120?, 0xc00019a2b0?, 0xc000198c50?}, {0x67c860, 0xc000198be0, 0x199}, {0x67c860, 0xc000198c50, 0x199})
        /usr/local/go/src/reflect/value.go:2255 +0x391
github.com/fxamacker/cbor/v2.(*decoder).parseMapToMap(0xc000311f30, {0x670120?, 0xc00019a2b0?, 0x0?}, 0xc000196d20)
        /home/agaffney/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.4.0/decode.go:1295 +0x9a9
github.com/fxamacker/cbor/v2.(*decoder).parseToValue(0xc000311f30, {0x670120?, 0xc00019a2b0?, 0xc00031a000?}, 0x0?)
        /home/agaffney/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.4.0/decode.go:782 +0xef8
...
```
