### ISSUE TITLE
Protocol setState send on closed channel

### ISSUE THREAD

**Issue by safanaj** [blinklabs-io/gouroboros#249]
Not sure if this is related to #224 
```
panic: send on closed channel

goroutine 39 [running]:
github.com/blinklabs-io/gouroboros/protocol.(*Protocol).setState(0xc0001801c0, {0xc00016e100?, {0x5d7118?, 0x40?}})
	/home/marco/.local/gocode/pkg/mod/github.com/blinklabs-io/gouroboros@v0.38.2/protocol/protocol.go:392 +0x1b5
github.com/blinklabs-io/gouroboros/protocol.(*Protocol).sendLoop(0xc0001801c0)
	/home/marco/.local/gocode/pkg/mod/github.com/blinklabs-io/gouroboros@v0.38.2/protocol/protocol.go:261 +0x85c
created by github.com/blinklabs-io/gouroboros/protocol.(*Protocol).Start
	/home/marco/.local/gocode/pkg/mod/github.com/blinklabs-io/gouroboros@v0.38.2/protocol/protocol.go:123 +0x276
```

This happens randomly , I tested it with some chainsync calls, the below code can be use to reproduce (at random):
```
func main() {
	ctx := context.Background()
	address := "<relay:port>"
	conn, err := (&net.Dialer{Timeout: time.Second}).DialContext(ctx, "tcp", address)
	if err != nil {
		panic(err)
	}

	o, _ := ouroboros.New(
		ouroboros.WithConnection(conn),
		ouroboros.WithNetwork(ouroboros.NetworkByName("mainnet")),
		ouroboros.WithNodeToNode(true),
		ouroboros.WithKeepAlive(true),
	)

	o.ChainSync().Client.Start()

	tip, err := o.ChainSync().Client.GetCurrentTip()
	if err != nil {
		o.Close()
		panic(err)
	}

	err = o.ChainSync().Client.Sync([]common.Point{tip.Point})
	if err != nil {
		o.Close()
		panic(err)
	}
	select {}
}
```
the exected panic here is, on purpose: `chain intersection not found` , every 5 execution I get at least 1 `send on closed channel` unexpected panic as explained above.

**Comment by safanaj** [comment]
The send on closed channel is caused by sendLoop calling setState, [here](https://github.com/blinklabs-io/gouroboros/blob/54674b97728215a5aac973cb50608720c7b07efa/protocol/protocol.go#L260) , the sendLoop is also closing the muxerSendChan [here](https://github.com/blinklabs-io/gouroboros/blob/54674b97728215a5aac973cb50608720c7b07efa/protocol/protocol.go#L160) before to exit, so to prevent this unexpected panic I just added the line to wait for the muxerSendChan in the protocol cleanup, like:
```
<-p.muxerSendChan
```
before the line that is closing the `p.recvReadyChan`, [here](https://github.com/blinklabs-io/gouroboros/blob/54674b97728215a5aac973cb50608720c7b07efa/protocol/protocol.go#L108)
