### ISSUE TITLE
keep-alive panic on closed connection

### ISSUE THREAD

**Issue by agaffney** [blinklabs-io/gouroboros#463]
This happens after a connection terminates remotely and the keep-alive client is running

```
panic: send on closed channel

goroutine 371 [running]:
github.com/blinklabs-io/gouroboros/protocol.(*Protocol).SendMessage(...)
        /home/agaffney/dev/blinklabs-io/gouroboros/protocol/protocol.go:174
github.com/blinklabs-io/gouroboros/protocol/keepalive.(*Client).sendKeepAlive(0xc00040aa50)
        /home/agaffney/dev/blinklabs-io/gouroboros/protocol/keepalive/client.go:82 +0x65
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x2d
```

**Comment by agaffney** [comment]
This particular panic was addressed elsewhere
